export interface Ingredient {
  slug: string;
  name: string;
  family: string;
  flavor: string;
  seasons: string[];
  storage: string;
  notes: string;
  goesWith: string[];
}

export const INGREDIENTS: Ingredient[] = [
  {
    slug: "basmati",
    name: "Basmati rice",
    family: "Grain",
    flavor: "Nutty, aromatic, long slender grains",
    seasons: ["year-round"],
    storage: "Airtight, cool and dry",
    notes: "The biryani base; ageing concentrates the aroma.",
    goesWith: ["saffron", "kewra water", "yak-mutton"],
  },
  {
    slug: "bufala-mozzarella",
    name: "Bufala mozzarella",
    family: "Dairy",
    flavor: "Milky, tender, faintly sweet",
    seasons: ["year-round"],
    storage: "In its liquid, refrigerated; use within days",
    notes: "Water buffalo milk; weep-proof and delicate. Fior di latte is the cow's-milk stand-in.",
    goesWith: ["basil", "san marzano", "00 flour"],
  },
  {
    slug: "san-marzano",
    name: "San Marzano tomato",
    family: "Produce",
    flavor: "Sweet, low-acid, dense flesh",
    seasons: ["summer"],
    storage: "Cool pantry, then fridge once opened",
    notes: "The pizza and ragù backbone; canned is the reliable standard.",
    goesWith: ["basil", "bufala mozzarella", "olive oil"],
  },
  {
    slug: "guajillo",
    name: "Guajillo chile",
    family: "Spice",
    flavor: "Berry-like, mild heat, woody",
    seasons: ["year-round"],
    storage: "Airtight, dark",
    notes: "A core of the al-pastor marinade; toasts fast, watch it.",
    goesWith: ["achiote", "pineapple", "pork"],
  },
  {
    slug: "ají-amarillo",
    name: "Ají amarillo",
    family: "Produce",
    flavor: "Fruity, floral, medium heat",
    seasons: ["year-round"],
    storage: "Refrigerate fresh; paste keeps long",
    notes: "Peru's yellow chile; depth behind ceviche and causas.",
    goesWith: ["lime", "cilantro", "white fish"],
  },
  {
    slug: "kombu",
    name: "Kombu",
    family: "Sea vegetable",
    flavor: "Salty-marine umami",
    seasons: ["year-round"],
    storage: "Airtight, cool and dry",
    notes: "Dashi's first voice; never boiled, only steeped.",
    goesWith: ["katsuobushi", "miso", "tofu"],
  },
  {
    slug: "katsuobushi",
    name: "Katsuobushi (bonito flakes)",
    family: "Seafood",
    flavor: "Smoky, fishy, umami",
    seasons: ["year-round"],
    storage: "Sealed, cool; re-seal fast",
    notes: "Dressed, fermented skipjack; the second voice of dashi.",
    goesWith: ["kombu", "miso", "scallion"],
  },
  {
    slug: "kewra-water",
    name: "Kewra water",
    family: "Fragrance",
    flavor: "Heady pandan-like perfume",
    seasons: ["year-round"],
    storage: "Cool, dark, sealed",
    notes: "Lucknow's biryani signature; a little goes a long way.",
    goesWith: ["basmati", "mace", "lamb"],
  },
  {
    slug: "saffron",
    name: "Saffron",
    family: "Spice",
    flavor: "Honeyed, metallic, hay-like",
    seasons: ["autumn harvest"],
    storage: "Airtight, dark, dry",
    notes: "Pricey by weight, tiny by dose. Soak threads in warm milk or water first.",
    goesWith: ["basmati", "rose water", "lamb"],
  },
  {
    slug: "tamarind",
    name: "Tamarind",
    family: "Produce",
    flavor: "Sour, fruity, sweet-dark",
    seasons: ["winter harvest"],
    storage: "Block keeps long; paste refrigerates",
    notes: "The pad-thai sour; use pulp dissolved in warm water.",
    goesWith: ["palm sugar", "fish sauce", "rice noodles"],
  },
  {
    slug: "palm-sugar",
    name: "Palm sugar",
    family: "Sweetener",
    flavor: "Caramel-woody sweetness",
    seasons: ["year-round"],
    storage: "Airtight; softens with warmth",
    notes: "Jaggery's neighbor; brown sugar is the honest swap.",
    goesWith: ["tamarind", "fish sauce", "thai lime"],
  },
  {
    slug: "yogurt",
    name: "Yogurt",
    family: "Dairy",
    flavor: "Clean tang, cooling richness",
    seasons: ["year-round"],
    storage: "Refrigerate",
    notes: "Marinate tenderizer and table sauce; strain for thicker body.",
    goesWith: ["lamb", "garlic", "sumac"],
  },
  {
    slug: "oat-bulgur",
    name: "Bulgur",
    family: "Grain",
    flavor: "Nutty, chewy, wheaty",
    seasons: ["year-round"],
    storage: "Airtight, cool and dry",
    notes: "Cracked, par-cooked wheat; the kibbeh shell body.",
    goesWith: ["lamb", "pine nuts", "seven-spice"],
  },
  {
    slug: "palm-oil",
    name: "Palm oil",
    family: "Oil",
    flavor: "Terracotta-colored, rich, savory",
    seasons: ["year-round"],
    storage: "Cool, dark",
    notes: "The color and soul of West African one-pot cooking.",
    goesWith: ["scotch bonnet", "tomato", "rice"],
  },
  {
    slug: "02c-corner-flour",
    name: "00 flour",
    family: "Grain",
    flavor: "Neutral, fine, silky",
    seasons: ["year-round"],
    storage: "Airtight, cool and dry",
    notes: "Double-zero pizza flour; strong dough, chewy crumb.",
    goesWith: ["san marzano", "bufala mozzarella", "yeast"],
  },
  {
    slug: "long-grain-rice",
    name: "Long-grain rice",
    family: "Grain",
    flavor: "Mild, separate grains",
    seasons: ["year-round"],
    storage: "Airtight, cool and dry",
    notes: "Jollof's canvas — absorbs color without turning sticky.",
    goesWith: ["palm oil", "scotch bonnet", "smoked fish"],
  },
  {
    slug: "maise-flour",
    name: "Fermented corn (maize)",
    family: "Grain",
    flavor: "Sour-dense, cooked-corn",
    seasons: ["year-round"],
    storage: "Sealed; ferments in use",
    notes: "Kenkey's base; the sourness comes from real fermentation.",
    goesWith: ["groundnut", "smoked fish", "leafy greens"],
  },
  {
    slug: "egg-taglierini",
    name: "Fresh egg pasta",
    family: "Grain",
    flavor: "Rich, tender, silky",
    seasons: ["year-round"],
    storage: "Fridge, floured; freeze for later",
    notes: "Tagliatelle's whole-genre canvas; roll thin, be proud.",
    goesWith: ["pork", "beef", "parmesan"],
  },
  {
    slug: "pike",
    name: "Pike (freshwater fish)",
    family: "Seafood",
    flavor: "Mild, firm, flaky",
    seasons: ["cool season"],
    storage: "Refrigerate; cook same day",
    notes: "The classic quenelle; firm white fish substitutes well.",
    goesWith: ["butter", "cream", "gruyère"],
  },
  {
    slug: "aleppo-pepper",
    name: "Aleppo pepper",
    family: "Spice",
    flavor: "Mild, fruity, salty-bright",
    seasons: ["year-round"],
    storage: "Airtight, dark",
    notes: "The finishing pepper of Istanbul's table.",
    goesWith: ["tomato", "butter", "yogurt"],
  },
  {
    slug: "thai-basil",
    name: "Thai basil",
    family: "Herb",
    flavor: "Anise-clove, warm, slightly sweet",
    seasons: ["warm season"],
    storage: "Fragile; wrap and refrigerate briefly",
    notes: "Distinct from regular basil — add at the very end.",
    goesWith: ["chicken", "chile", "fish sauce"],
  },
  {
    slug: "fermented-soy",
    name: "Soy (shoyu)",
    family: "Fermented condiment",
    flavor: "Salty, umami, caramel",
    seasons: ["year-round"],
    storage: "Cool, dark, sealed",
    notes: "The elderly of the condensed-flavor family; brew matters.",
    goesWith: ["ginger", "garlic", "sugar"],
  },
  {
    slug: "miso",
    name: "Miso",
    family: "Fermented",
    flavor: "Savory, living salt",
    seasons: ["year-round"],
    storage: "Refrigerate, sealed",
    notes: "White (shiro) is mellow, red (aka) is punchy. Stir in off heat.",
    goesWith: ["tofu", "kombu", "scallion"],
  },
];

export function getIngredient(slug: string): Ingredient | undefined {
  return INGREDIENTS.find((ingredient) => ingredient.slug === slug);
}

export function ingredientsForRecipeItem(name: string): Ingredient | undefined {
  const needle = name.toLowerCase();
  return INGREDIENTS.find(
    (ingredient) => needle.includes(ingredient.name) || ingredient.name.includes(needle)
  );
}